Feature/graphql users
vtex-apps/b2b-organizations-graphql pull request #29
Opened 2022-04-08 15:01 UTC by arturmagalhaesjr

#### What problem is this solving?

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2022-04-11 20:59 UTC, polishq requested changes
In addition to the two minor changes in the comments, I think we missed something when we updated `vtex.storefront-permissions`. Part of the reason for splitting the `saveUser` mutation into `add` and `update` mutations was so that we could prevent a user from being moved from one organization to another (either accidentally or maliciously). With the latest code I'm still able to "add" a user that already belongs to another organization or has a different role in the same organization, and their existing org/cost/role will be overwritten with the new ones. The "add" operation should only be allowed if the user has no org/cost/role assigned.

2022-04-11 20:59 UTC, polishq commented on node/clients/storefrontPermissions.ts
> +      id
```suggestion
      id
      status
      message
```

2022-04-11 20:59 UTC, polishq commented on node/clients/storefrontPermissions.ts
> +      id
```suggestion
      id
      status
      message
```

2022-04-12 12:48 UTC, arturmagalhaesjr reviewed
Done!
Also, I've opened this PR: https://github.com/vtex-apps/storefront-permissions/pull/43/files to cover the feature that I mentioned regarding a validation.

2022-04-14 17:54 UTC, polishq approved these changes
LGTM

2022-04-15 12:40 UTC, merged